version: 2

jobs:
  build:
    working_directory: /go/src/github.com/splunk/qbec
    docker:
      - image: circleci/golang:1.13
    environment:
      - GOCACHE: /tmp/go/cache
    steps:
      - checkout
      - restore_cache:
          keys:
            - go13-pkg-cache
      - run:
          name: Install command dependencies
          command: make install-ci install
      - run:
          name: Install package dependencies
          command: make get
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make lint
      - save_cache:
          key: go13-pkg-cache
          paths:
          - "/go/pkg"
workflows:
  version: 2
  workflow:
    jobs:
      - build: {}
